export function getSourceName(sourceId: string): string {
  const sourceNames: Record<string, string> = {
    'zuida': '最大資源',
    'wujin': '無盡資源',
    'tianya': '天涯資源',
    'baofeng': '暴風資源',
    'jisu': '極速資源',
    'baiduyun': '百度雲資源',
    'ruyi': '如意資源',
    'wolong': '臥龍資源',
    'dytt': '電影天堂',
    'modu': '魔都資源',
    'wangwang': '旺旺資源',
    'hongniu': '紅牛資源',
    'guangsu': '光速資源',
    'jiangyu': '鯨魚資源',
    'sanliuling': '360資源',
    'haihua': '海豚資源',
    'wujin2': '無盡ME',
    'tianyazy': '天涯海角',
    'guangsu2': '光速HTTP',
    'youku': '優酷資源',
    'yilingba': '1080資源',
    'huya': '虎牙資源',
    'xinlang': '新浪資源',
    'ikun': 'iKun資源',
    'lezi': '樂子資源',
    'xinlang2': '新浪HTTPS',
    'yilingba2': '1080JSON',
    'baofeng2': '暴風APP',
    'wolong2': '臥龍採集',
    'lezi2': '樂子HTTP',
    'feifan': '非凡資源',
    'aidan': '愛蛋資源',
    'feifanapi': '非凡API',
    'feifancj': '非凡採集',
    'feifancj2': '非凡採集HTTPS',
    'feifan1': '非凡線路1',
    'moduzy': '魔都影視',
    'leba': '樂播資源',
  };
  return sourceNames[sourceId] || sourceId;
}

export const SOURCE_IDS = [
  'zuida', 'wujin', 'tianya', 'baofeng', 'jisu', 'baiduyun',
  'ruyi', 'wolong', 'dytt', 'modu', 'wangwang', 'hongniu',
  'guangsu', 'jiangyu', 'sanliuling', 'haihua', 'wujin2', 'tianyazy',
  'guangsu2', 'youku', 'yilingba', 'huya', 'xinlang', 'ikun',
  'lezi', 'xinlang2', 'yilingba2', 'baofeng2', 'wolong2', 'lezi2',
  'feifan', 'aidan', 'feifanapi', 'feifancj', 'feifancj2', 'feifan1',
  'moduzy', 'leba'
];
